### ISSUE TITLE
Following page doesn't load

### ISSUE THREAD

**Issue by lukepighetti** [GroovinChip/GitHub-Activity-Feed#68]
Been loading for about a minute. Ideally would be less than 3 seconds

![IMG_BC67512C3D5B-1](https://user-images.githubusercontent.com/666539/83290172-3c88b980-a1b4-11ea-9a8a-56532f21ad04.jpeg)

**Comment by GroovinChip** [comment]
This is related to issues #57 and #58

**Comment by GroovinChip** [comment]
@lukepighetti check out the latest release and see what happens. You will likely encounter issue #85 but opening the app afterwards should result in normal behavior.
