### ISSUE TITLE
Blank screen after signining in

### ISSUE THREAD

**Issue by humble-git** [GroovinChip/GitHub-Activity-Feed#81]
Hi,

I downloaded the app from the releases. After installing and singin in app only shows blank screen. 

I'm using Android 10 on my device.

**Comment by GroovinChip** [comment]
This is the latest version, correct? Do you see a loading spinner?

**Comment by humble47** [comment]
no i see nothing when i login, i tried reinstalling app same issue

**Comment by GroovinChip** [comment]
Hi @humble-git I know it's been a long time, but please check out the [newest release](https://github.com/GroovinChip/GitHub-Activity-Feed/releases/tag/0.5.0). Besides for the post-login crash that I am investigating, the feed works much better. Please let me know what you think.

**Comment by humble-git** [comment]
Yep, it seems to work fine now. Thanks.  
It does crash though after logging, but I see you already know that. 
Closing Issue

**Comment by GroovinChip** [comment]
Glad to see it's working for you. Yeah, I'm investigating the post-login crash in #85.
