### ISSUE TITLE
App Crashes when tapped on Search button 

### ISSUE THREAD

**Issue by humble-git** [GroovinChip/GitHub-Activity-Feed#88]
App Crashes when i tap on search button, 
Device: Android Emulator - Pixel C API 30

**Comment by GroovinChip** [comment]
It crashed when you tapped the search button or when you started typing? If you're using an emulator I assume you're doing dev work? If so, did you get a stack trace?

**Comment by GroovinChip** [comment]
Ok, I've experienced this myself now. Will investigate.

**Comment by GroovinChip** [comment]
@humble-git check out the [latest release](https://github.com/GroovinChip/GitHub-Activity-Feed/releases/tag/0.6.1) and let me know if the problem persists.

**Comment by humble-git** [comment]
Hey @GroovinChip 
Nope still same issue, attached GIF for your reference 
![git activity feed crash](https://user-images.githubusercontent.com/67156984/106171931-2d7d5f80-61b8-11eb-8acf-7efae452a023.gif)

**Comment by GroovinChip** [comment]
Thanks @humble-git I'll keep looking into it

**Comment by GroovinChip** [comment]
@humble-git check out the latest release, 0.8.2, the issue is fixed now.
